### ISSUE TITLE
[Bug]: B站视频总结消息合并转发失败

### ISSUE THREAD

**Issue by llllin2333** [zhiyu1998/nonebot-plugin-resolver#16]
### 这个问题是否已经存在？

- [X] 我已经搜索过现有的问题 (https://gitee.com/../../issues)

### 如何复现

填写b站配置后，发送视频总结消息LLQQNT会报错

### 实际结果

```
10-11 10:30:24 [INFO] nonebot-plugin-resolver | 正在合并：['C:\\Users\\Administrator\\Desktop\\ELF_RSS/BV1qb2VYWEKL-res.mp4']
10-11 10:30:24 [INFO] nonebot-plugin-resolver | {'BV1qb2VYWEKL-video.m4s': 'remove', 'BV1qb2VYWEKL-audio.m4s': 'remove'}
10-11 10:30:27 [INFO] nonebot | Matcher(type='message', module=src.plugins.nonebot-plugin-resolver, lineno=58) running complete
10-11 10:30:27 [ERROR] nonebot | Running Matcher(type='message', module=src.plugins.nonebot-plugin-resolver, lineno=58) failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\ELF_RSS\bot.py", line 11, in <module>
    nonebot.run(app="__mp_main__:app")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\main.py", line 579, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Desktop\ELF_RSS\src\plugins\nonebot-plugin-resolver\__init__.py", line 109, in wrapper
    return await func(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\ELF_RSS\src\plugins\nonebot-plugin-resolver\__init__.py", line 327, in bilibili
    await bili23.send(Message(send_forword_summary))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 566, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 237, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 190, in send
    return await bot.send_msg(**params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\internal\adapter\bot.py", line 122, in call_api
    raise exception
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\internal\adapter\bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 147, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1200, data=None, message='Error: 请使用 /send_group_forward_msg 或 /send_private_forward_msg 进行合并转发\n    at SendMsg._handle (C:\\Users\\Administrator\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:360:58114)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async SendMsg.websocketHandle (C:\\Users\\Administrator\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:360:51765)\n    at async OB11WebSocketReverse.handleAction (C:\\Users\\Administrator\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:21:26191)', wording='Error: 请使用 /send_group_forward_msg 或 /send_private_forward_msg 进行合并转发\n    at SendMsg._handle (C:\\Users\\Administrator\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:360:58114)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async SendMsg.websocketHandle (C:\\Users\\Administrator\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:360:51765)\n    at async OB11WebSocketReverse.handleAction (C:\\Users\\Administrator\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:21:26191)', echo='28')
```

### 截图或视频
![image](https://github.com/user-attachments/assets/4f602f2d-4695-49e1-aff7-6820643dc4db)

### 插件版本号

nonebot-plugin-resolver 1.2.20

### 适配器类型

LLOneBot

### Python版本

Python3.11以上

### 系统

windows

**Comment by zhiyu1998** [comment]
提供下样本BV号，BVxxxxx

**Comment by llllin2333** [comment]
> 提供下样本BV号，BVxxxxx

BV1qb2VYWEKL
尝试过卸载重装qq和LLonebot还是一样的报错
仅B站视频总结消息无法发送，其他解析的合并转发正常
![image](https://github.com/user-attachments/assets/0eedb825-6b10-44a7-b028-cea77e712988)
![image](https://github.com/user-attachments/assets/d916a770-9bad-440b-9e4b-c76837555556)

**Comment by Priopus** [comment]
根据llob侧issues反馈建议更新v.4.0.9版本尝试解决合并转发报错的问题
